"""
knowledge_hub/store.py — the swappable Knowledge-Hub store interface (#26).

``HubStore`` is the contract every backend must satisfy: the JSON-backed
``KnowledgeHub`` today, a **QLEVER triple-store** at WP4. Agents and the
module-level ``hub.*`` helpers reach the store only through ``hub.get_store()``,
so swapping the backend (via ``config.KH_BACKEND``) never touches agent code.

To add a backend: implement every method below, then wire it into
``hub.get_store()`` under a new ``KH_BACKEND`` value. The Protocol is
``runtime_checkable``, so tests can assert conformance with ``isinstance``.
"""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class HubStore(Protocol):
    # ── lookups (read) ────────────────────────────────────────────────────────
    def search_person(self, name: str) -> list[dict]: ...
    def search_place(self, name: str) -> list[dict]: ...
    def find_person(self, name: str) -> Optional[dict]: ...
    def find_place(self, name: str) -> Optional[dict]: ...
    def match_vocabulary(self, term: str) -> Optional[str]: ...

    # ── enumeration (read) ────────────────────────────────────────────────────
    def get_persons(self) -> list[dict]: ...
    def get_places(self) -> list[dict]: ...
    def all_persons(self) -> list: ...
    def all_places(self) -> list: ...
    def all_vocabulary(self) -> list: ...

    # ── mutation (write) ──────────────────────────────────────────────────────
    def add_person(self, person: dict) -> None: ...
    def add_place(self, place: dict) -> None: ...
    def add_keyword(self, term: str) -> None: ...
    def add_document_type(self, dtype: str) -> None: ...

    # ── introspection ─────────────────────────────────────────────────────────
    def summary(self) -> str: ...
